server:
  servlet:
    context-path: /product
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/product"
    username: root
    password: Thanhhai
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true